### ISSUE TITLE
File issues to clarify STREAM behavior

### ISSUE THREAD

**Issue by sappenin** [hyperledger/quilt#325]
The following clarifications need to be made in the STREAM RFC and implementations:

# Java Issues
- [x] File issue to Ignore any new ConnectionAssetDetails frames after the first one (see https://github.com/hyperledger/quilt/issues/326)

# Rust Issues
- [x] File issue to start sending ConnectionAssetDetails from the StatelessStreamReceiver (see https://github.com/interledger-rs/interledger-rs/issues/395).
- [x] File issue to add ConnectionAssetDetails to the SPSP response (see https://github.com/interledger-rs/interledger-rs/issues/396)

# RFC Issues
(Instigating Issue: https://github.com/interledger/rfcs/issues/546)
- [x] Update the [RFC](https://github.com/interledger/rfcs/blob/master/0029-stream/0029-stream.md) to indicate why CAD is optional (e.g., This is not needed for a Web monetization connection.)
- [x] Update the [RFC](https://github.com/interledger/rfcs/blob/master/0029-stream/0029-stream.md) to indicate that only a single ConnectionAssetDetails should be accepted per connection, with the rest being ignored (Assume new ILP addreses don't change asset code/scale.)
- [x] Update the [RFC](https://github.com/interledger/rfcs/blob/master/0029-stream/0029-stream.md) to clarify the definition of a Connection.

**Comment by sappenin** [comment]
This is complete per the links above.
